version: '3.8'

services:
  # 1. Le Data Warehouse (Base de données)
  postgres:
    image: postgres:15
    container_name: dwh_postgres
    restart: always # Si le conteneur plante, Docker le redémarre tout seul
    env_file:
      - .env # Injecte les mots de passe de notre fichier caché
    ports:
      - "5432:5432" # Redirige le port 5432 du conteneur vers le port 5432 de votre PC
    volumes:
      - postgres_data:/var/lib/postgresql/data # PERSISTANCE : Si le conteneur est détruit, les données survivent virtuellement ici !
    networks:
      - data_network

  # 2. L'Interface Graphique 
  pgadmin:
    image: dpage/pgadmin4
    container_name: dwh_pgadmin
    restart: always
    env_file:
      - .env
    ports:
      - "5050:80" # Redirige le port 80 web du conteneur vers le port 5050 de votre PC
    networks:
      - data_network
    depends_on:
      - postgres # Assure que PgAdmin ne démarre que SI Postgres a fini de démarrer

  # 3. L'Orchestrateur Apache Airflow (Le Chef d'Orchestre)
  airflow:
    image: apache/airflow:2.8.2-python3.10
    container_name: orchestrator_airflow
    restart: always
    env_file:
      - .env
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db # Simplification de la base de données interne d'Airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW_WWW_USER_USERNAME=admin   # Création du compte "admin"
      - AIRFLOW_WWW_USER_PASSWORD=admin
      # ASTUCE DATA ENGINEER: Installation à la volée des librairies Python dans le conteneur Airflow !
      - _PIP_ADDITIONAL_REQUIREMENTS=pandas sqlalchemy psycopg2-binary requests beautifulsoup4 dbt-postgres==1.7.0
      - DB_HOST=dwh_postgres # On dit aux scripts Python que Postgres s'appelle "dwh_postgres" dans le réseau Docker
    volumes:
      # On "partage" les dossiers de notre PC avec le conteneur Airflow (volume mounts)
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data
      - ./ecommerce_dbt:/opt/airflow/ecommerce_dbt
    ports:
      - "8081:8080" # Airflow tourne sur le port 8080 de son côté, projeté sur votre port 8081
    command: standalone # Démarrage magique d'Airflow, sans architecture lourde. Parfait pour les étudiants.
    networks:
      - data_network
    depends_on:
      - postgres

# On crée un réseau privé virtuel pour que pgadmin puisse "parler" à postgres sans passer par l'extérieur
networks:
  data_network:
    driver: bridge

# On définit explicitement un volume physique persistant pour la base
volumes:
  postgres_data: